import { CharacterEquipmentComponent } from './character-equipment.component';
import { upgradeEquipmentTypes } from '../../services/equipment-types';
import { MultiselectComponent } from '../../../shared/components/multiselect/multiselect.component';
import { By } from '@angular/platform-browser';
import { EquipmentEditorComponent } from './equipment-editor.component';
import { newFlag, variableKey } from '../../models/story.model';
import { TestBed } from '@angular/core/testing';
import { DialogService } from '../../../shared/services/dialog.service';
import { StoryManagerSerializationService } from '../../services/story-manager-serialization.service';
import { inventoryFixture } from '../../engine/story-inventory-fixture';
import { applyEffect, startGame } from '../../engine/story-engine';
import { InventoryEditorComponent } from './inventory-editor.component';
import { ReorderComponent } from './reorder.component';
import { PlayerComponent } from './player.component';
import { OutcomeEditorComponent } from './outcome-editor.component';
import { ConditionEditorComponent } from './condition-editor.component';
import { TextEditorComponent } from './text-editor.component';
import { EntityFlagsComponent } from './entity-flags.component';
import { copy, always, newPassage } from '../../models/story.model';

describe('Inventory authoring and reader controls', () => {
  let dialogs: { createConfirmation: jasmine.Spy; createInput: jasmine.Spy }, persistence: any;
  beforeEach(async () => {
    dialogs = { createConfirmation: jasmine.createSpy().and.resolveTo(true), createInput: jasmine.createSpy().and.resolveTo('Protected from curses') };
    persistence = { data: { playthroughs: [] }, commit: jasmine.createSpy() };
    await TestBed.configureTestingModule({
      imports: [InventoryEditorComponent, ReorderComponent, PlayerComponent, OutcomeEditorComponent, ConditionEditorComponent],
      providers: [
        { provide: DialogService, useValue: dialogs },
        { provide: StoryManagerSerializationService, useValue: persistence },
      ],
    }).compileComponents();
  });
  it('adds to an existing carried stack without creating copies or reassigning another character', async () => {
    const f = TestBed.createComponent(InventoryEditorComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities[0];
    c.selected = 'apple';
    c.add();
    c.selected = 'apple';
    c.add();
    f.detectChanges();
    await f.whenStable();
    expect(c.entity.inventory.filter((r) => r.target === 'apple').map((r) => r.quantity)).toEqual([7]);
    expect(c.story.copies.filter((i) => i.owner === 'npc').length).toBe(2);
    expect(dialogs.createConfirmation).not.toHaveBeenCalled();
    expect(f.nativeElement.textContent.toLowerCase()).not.toContain('unique');
    c.entity.inventory[0].quantity = Number.MAX_SAFE_INTEGER;
    c.selected = 'apple';
    c.add();
    expect(c.entity.inventory[0].quantity).toBe(Number.MAX_SAFE_INTEGER);
  });
  it('offers only variants for character copies and only types as variant defaults', () => {
    const story = inventoryFixture();
    upgradeEquipmentTypes(story);
    const type = story.entities.find((e) => e.equipmentRole === 'type');
    const variant = story.entities.find((e) => e.id === 'dagger');
    const c = TestBed.createComponent(CharacterEquipmentComponent).componentInstance;
    c.story = story;
    c.entity = story.entities[0];
    const count = story.copies.length;
    expect(c.templates).toEqual([variant]);
    c.selected = type.id;
    c.addCopy();
    expect(story.copies.length).toBe(count);
    c.selected = variant.id;
    c.addCopy();
    expect(story.copies.at(-1).definition).toBe(variant.id);
    const editor = TestBed.createComponent(EquipmentEditorComponent).componentInstance;
    editor.story = story;
    editor.entity = variant;
    expect(editor.parents).toEqual([type]);
    editor.setParent(variant.id);
    expect(variant.parentId).toBe(type.id);
  });
  it('switches the persistent sidebar without saving and updates it after equip, unequip and undo', async () => {
    const fixture = TestBed.createComponent(PlayerComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    c.testScene = c.story.start;
    c.ngOnChanges();
    await c.start();
    const before = JSON.stringify(c.game);
    fixture.detectChanges();
    const buttons = Array.from(fixture.nativeElement.querySelectorAll('.gear-switch button') as NodeListOf<HTMLButtonElement>);
    expect(fixture.nativeElement.querySelector('.inventory-view')).not.toBeNull();
    expect(fixture.nativeElement.querySelector('.equipment-view')).toBeNull();
    buttons[1].click();
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.inventory-view')).toBeNull();
    expect(fixture.nativeElement.querySelector('.equipment-view').textContent).toContain('No equipped items.');
    expect(buttons[1].getAttribute('aria-pressed')).toBe('true');
    expect(JSON.stringify(c.game)).toBe(before);
    expect(persistence.commit).not.toHaveBeenCalled();
    await c.changeEquipment('dagger-1', true);
    fixture.detectChanges();
    expect(c.gearView).toBe('equipment');
    expect(c.equipment.map((e) => e.id)).toContain('dagger-1');
    expect(fixture.nativeElement.querySelector('.equipment-view').textContent).toContain('Unequip');
    await c.changeEquipment('dagger-1', false);
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.equipment-view').textContent).toContain('No equipped items.');
    c.undo();
    fixture.detectChanges();
    expect(c.equipment.map((e) => e.id)).toContain('dagger-1');
    buttons[0].click();
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.inventory-view')).not.toBeNull();
    expect(c.inventory.map((e) => e.id)).not.toContain('dagger-1');
  });
  it('always shows item descriptions and actions without changing the playthrough', async () => {
    const fixture = TestBed.createComponent(PlayerComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    const original = startGame(c.story, 'Reader');
    persistence.data.playthroughs = [original];
    fixture.detectChanges();
    const before = JSON.stringify(c.game);
    const row = fixture.nativeElement.querySelector('[data-item-id="dagger-1"]') as HTMLElement;
    const header = row.querySelector<HTMLElement>('.gear-row-header');
    expect(row.tagName).toBe('ARTICLE');
    expect(row.querySelector('summary')).toBeNull();
    expect(header.querySelector('button')).toBeNull();
    expect(header.textContent.trim()).toContain('Dagger 1');
    header.click();
    fixture.detectChanges();
    expect(row.querySelector('.gear-description').textContent).toBe('Description of dagger');
    expect(row.querySelector('.gear-action').textContent.trim()).toBe('Equip');
    expect(row.textContent).toContain('Durability');
    expect(row.textContent).not.toContain('Private');
    expect(JSON.stringify(c.game)).toBe(before);
    expect(persistence.commit).not.toHaveBeenCalled();
  });
  it('keeps dialogue and decisions visible above choices as the story advances and undoes', async () => {
    const fixture = TestBed.createComponent(PlayerComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    const scene = c.story.scenes[0],
      first = scene.passages[0],
      next = newPassage();
    first.text = 'Take the path beside [[object:apple]].';
    first.choices[0].label = 'Follow the path';
    first.choices[0].steps = [{ id: 'continue', kind: 'go', scene: scene.id, passage: next.id }];
    next.text = 'You reach the gate.';
    next.choices = [copy(first.choices[0])];
    next.choices[0].id = 'finish-choice';
    next.choices[0].label = 'Open the gate';
    next.choices[0].steps = [{ id: 'finish', kind: 'end' }];
    scene.passages.push(next);
    c.testScene = scene.id;
    c.ngOnChanges();
    await c.start();
    fixture.detectChanges();
    await c.select(first.choices[0].id);
    fixture.detectChanges();
    const transcript = fixture.nativeElement.querySelector('.transcript') as HTMLElement;
    expect(transcript.querySelectorAll('.transcript-entry:not(.player-action)').length).toBe(2);
    expect(transcript.textContent).toContain('Take the path beside');
    expect(transcript.textContent).toContain('You reach the gate.');
    expect(transcript.querySelector('.player-decision').textContent).toContain('Follow the path');
    expect(transcript.querySelector('.player-decision h3').textContent).toBe('You');
    expect(transcript.parentElement.nextElementSibling.classList.contains('choices')).toBeTrue();
    expect(transcript.parentElement.nextElementSibling.textContent).toContain('Open the gate');
    expect(fixture.nativeElement.textContent).not.toContain('Show history');
    transcript.querySelector<HTMLButtonElement>('.link').click();
    expect(c.inspected).toBe('apple');
    await c.select(next.choices[0].id);
    fixture.detectChanges();
    expect(transcript.querySelectorAll('.player-decision').length).toBe(2);
    expect(fixture.nativeElement.querySelector('.choices')).toBeNull();
    c.undo();
    c.undo();
    fixture.detectChanges();
    expect(transcript.querySelectorAll('.transcript-entry').length).toBe(1);
    expect(transcript.querySelector('.player-decision')).toBeNull();
  });
  it('automatically resumes the newest legacy save and restarts it from the toolbar without creating a slot', async () => {
    const fixture = TestBed.createComponent(PlayerComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    const first = startGame(c.story, 'First'),
      second = startGame(c.story, 'Second');
    first.created = '2026-01-01T00:00:00.000Z';
    second.created = '2026-01-02T00:00:00.000Z';
    second.status = 'ended';
    second.transcript[0].choice = 'Previous decision';
    persistence.data.playthroughs = [first, second];
    persistence.commit.and.callFake(async (game) => {
      persistence.data.playthroughs = persistence.data.playthroughs.map((saved) => (saved.id === game.id ? game : saved));
    });
    fixture.detectChanges();
    expect(c.game.id).toBe(second.id);
    expect(fixture.nativeElement.querySelector('.saved-game')).toBeNull();
    expect(fixture.nativeElement.textContent).not.toContain('Second');
    const buttons = fixture.nativeElement.querySelectorAll('.player-toolbar button') as NodeListOf<HTMLButtonElement>;
    expect(buttons[0].textContent.trim()).toBe('Undo');
    expect(buttons[0].disabled).toBeTrue();
    expect(buttons[1].textContent.trim()).toBe('Restart');
    buttons[1].click();
    await fixture.whenStable();
    fixture.detectChanges();
    expect(dialogs.createConfirmation).toHaveBeenCalled();
    expect(c.game.id).toBe(second.id);
    expect(c.game.name).toBe('Second');
    expect(c.game.status).toBe('active');
    expect(c.game.transcript[0].choice).toBeUndefined();
    expect(persistence.data.playthroughs[0]).toBe(first);
    expect(persistence.data.playthroughs.length).toBe(2);
    expect(dialogs.createInput).not.toHaveBeenCalled();
  });
  it('creates only one playthrough and preserves it when a restart is canceled', async () => {
    const c = TestBed.createComponent(PlayerComponent).componentInstance;
    c.story = inventoryFixture();
    persistence.commit.and.callFake(async (game) => {
      persistence.data.playthroughs = [game];
    });
    await c.start();
    const original = copy(c.game);
    expect(persistence.data.playthroughs.length).toBe(1);
    expect(dialogs.createInput).not.toHaveBeenCalled();
    dialogs.createConfirmation.and.resolveTo(false);
    await c.start();
    expect(c.game).toEqual(original);
    expect(persistence.commit).toHaveBeenCalledTimes(1);
    dialogs.createConfirmation.and.resolveTo(true);
    await c.start();
    expect(c.game.id).toBe(original.id);
    expect(persistence.data.playthroughs.length).toBe(1);
  });
  it('saves undo for equipment and dialogue, keeps failed undo retryable, and clears undo after restart', async () => {
    const fixture = TestBed.createComponent(PlayerComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    const original = startGame(c.story, 'Playthrough');
    persistence.data.playthroughs = [original];
    const commit = async (game) => {
      persistence.data.playthroughs = [game];
    };
    persistence.commit.and.callFake(commit);
    await c.changeEquipment('dagger-1', true);
    const equipped = copy(c.game);
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.transcript .equipment-action').textContent).toContain('Equipped Dagger 1.');
    expect(fixture.nativeElement.querySelector('.equipment-action.player-action h3').textContent).toBe('You');
    await c.select(c.choices[0].id);
    expect(c.game.status).toBe('ended');
    fixture.detectChanges();
    const undo = fixture.nativeElement.querySelector('.player-toolbar button') as HTMLButtonElement;
    expect(undo.disabled).toBeFalse();
    undo.click();
    await fixture.whenStable();
    expect(c.game).toEqual(equipped);
    persistence.commit.and.rejectWith(new Error('Save failed'));
    await c.undo();
    expect(c.game).toEqual(equipped);
    expect(c.canUndo).toBeTrue();
    expect(c.error).toBe('Save failed');
    persistence.commit.and.callFake(commit);
    await c.undo();
    expect(c.game).toEqual(original);
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.transcript .equipment-action')).toBeNull();
    expect(c.canUndo).toBeFalse();
    await c.changeEquipment('dagger-1', true);
    await c.start();
    expect(c.undoStack.length).toBe(0);
    expect(c.canUndo).toBeFalse();
    expect(c.game.state).toEqual(original.state);
  });
  it('does not offer undo across a story revision or a different story', async () => {
    const c = TestBed.createComponent(PlayerComponent).componentInstance;
    c.story = inventoryFixture();
    persistence.data.playthroughs = [startGame(c.story, 'Playthrough')];
    persistence.commit.and.callFake(async (game) => {
      persistence.data.playthroughs = [game];
    });
    await c.changeEquipment('dagger-1', true);
    c.story.revision++;
    expect(c.canUndo).toBeFalse();
    await c.undo();
    expect(persistence.commit).toHaveBeenCalledTimes(1);
    c.ngOnChanges();
    expect(c.undoStack.length).toBe(0);
    c.story = { ...c.story, id: 'another-story' };
    expect(c.game).toBeUndefined();
  });
  it('groups inventory categories and only offers equipment for equipped checks and actions', async () => {
    const story = inventoryFixture();
    const inventory = TestBed.createComponent(InventoryEditorComponent);
    inventory.componentInstance.story = story;
    inventory.componentInstance.entity = story.entities[0];
    inventory.detectChanges();
    await inventory.whenStable();
    const groups = inventory.nativeElement.querySelectorAll('optgroup') as NodeListOf<HTMLOptGroupElement>;
    expect(Array.from(groups).map((g) => g.label)).toEqual(['Items']);
    expect(groups[0].textContent).toContain('apple');
    expect(groups[0].textContent).not.toContain('dagger');
    expect(inventory.nativeElement.textContent).not.toContain('Dagger 1');
    expect(inventory.nativeElement.querySelector('story-character-equipment')).toBeNull();
    const conditions = TestBed.createComponent(ConditionEditorComponent).componentInstance;
    conditions.story = story;
    conditions.condition = { ...always(), kind: 'owns' };
    expect(conditions.objects.some((e) => e.id === 'apple')).toBeTrue();
    conditions.condition.kind = 'wears';
    expect(conditions.objects.map((e) => e.id)).toEqual(story.copies.map((c) => c.id));
    const outcomes = TestBed.createComponent(OutcomeEditorComponent).componentInstance;
    outcomes.story = story;
    for (const kind of ['equip', 'unequip'] as const) expect(outcomes.effectObjects({ kind, target: '', actor: '', value: '' }).map((e) => e.id)).toEqual(story.copies.map((c) => c.id));
  });
  it('inserts and previews equipment references with a distinct token kind', () => {
    const c = TestBed.createComponent(TextEditorComponent).componentInstance;
    c.story = inventoryFixture();
    expect(c.references.find((r) => r.token === '[[equipment:dagger]]')).toBeTruthy();
    expect(c.references.find((r) => r.token === '[[object:dagger]]')).toBeUndefined();
    expect(c.references.find((r) => r.token === '[[object:apple]]')?.label).toBe('apple · item');
    c.text = '[[equipment:dagger]] and [[object:apple]]';
    expect(c.preview).toBe('dagger and apple');
  });
  it('allows equipped Boolean grants only in the equipment editor', async () => {
    const f = TestBed.createComponent(EntityFlagsComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities.find((e) => e.id === 'apple');
    c.setEffects(['armed']);
    f.detectChanges();
    await f.whenStable();
    expect(c.entity.flagGrants[0].when).toBe('owned');
    expect(f.nativeElement.textContent).not.toContain('Requires equipped');
    c.entity = c.story.entities.find((e) => e.id === 'dagger');
    f.detectChanges();
    expect(f.nativeElement.querySelector('app-multiselect')).not.toBeNull();
  });
  it('creates separate starting copies on Characters and edits inherited template defaults', async () => {
    const f = TestBed.createComponent(CharacterEquipmentComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities.find((e) => e.id === 'player');
    c.selected = 'dagger';
    c.addCopy();
    const instance = c.copies.at(-1);
    c.setCopyValue(instance, 'durability', 20);
    f.detectChanges();
    await f.whenStable();
    expect(f.nativeElement.textContent).toContain('Reset to equipment default');
    expect((Array.from(f.nativeElement.querySelectorAll('details.box')) as HTMLDetailsElement[]).at(-1).open).toBeTrue();
    expect(f.nativeElement.textContent).not.toContain('Quantity');
    expect(instance.owner).toBe('player');
    const game = startGame(c.story, 'Copies');
    expect(game.state.copyStates[instance.id].values['durability']).toBe(20);
    c.resetCopyValue(instance, 'durability');
    expect(startGame(c.story, 'Reset').state.copyStates[instance.id].values['durability']).toBe(100);
  });
  it('keeps Equipment focused on templates and inherited defaults', async () => {
    const f = TestBed.createComponent(EquipmentEditorComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities.find((e) => e.id === 'dagger');
    const copies = copy(c.story.copies);
    f.detectChanges();
    expect(f.nativeElement.textContent).not.toContain('Create copy');
    expect(f.nativeElement.textContent).not.toContain('Starting owner');
    expect([...f.nativeElement.querySelectorAll('h3')].some((h: HTMLElement) => h.textContent === 'Copies')).toBeFalse();
    const base = c.entity;
    c.story.entities.push({ ...copy(base), id: 'sharp', name: 'Sharp', parentId: base.id, requiredSlots: undefined, properties: [], flagGrants: [] });
    c.entity = c.story.entities[c.story.entities.length - 1];
    c.section = 'Variables';
    c.setOverride('durability', 80);
    c.setGrant('armed', 'off');
    f.detectChanges();
    await f.whenStable();
    expect(f.nativeElement.textContent).toContain('Reset to type default');
    expect(c.resolved.properties[0].initial).toBe(80);
    c.resetOverride('durability');
    expect(c.resolved.properties[0].initial).toBe(100);
    expect(c.resolved.flagGrants.some((g) => g.flag === 'armed')).toBeFalse();
    expect(c.parents.some((p) => p.id === 'sharp')).toBeFalse();
    expect(c.story.copies).toEqual(copies);
  });
  it('selects required layers with removable chips while preserving inherited and missing layers', async () => {
    const fixture = TestBed.createComponent(EquipmentEditorComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    c.story.slots.push('Extra layer');
    const parent = c.story.entities.find((e) => e.id === 'dagger');
    parent.requiredSlots = [c.story.slots[0], 'Missing'];
    c.entity = { ...copy(parent), id: 'variant', parentId: parent.id, properties: [], requiredSlots: undefined };
    c.story.entities.push(c.entity);
    fixture.detectChanges();
    await fixture.whenStable();
    fixture.detectChanges();
    const picker = fixture.debugElement.query(By.directive(MultiselectComponent)).componentInstance as MultiselectComponent;
    expect(picker.label).toBe('Required layers');
    expect(picker.disabled).toBeTrue();
    expect(picker.value).toEqual(parent.requiredSlots);
    expect(fixture.nativeElement.textContent).toContain('Missing layer: Missing');
    c.setSlots([]);
    expect(c.entity.requiredSlots).toBeUndefined();
    c.setSlotsOverride(true);
    fixture.detectChanges();
    await fixture.whenStable();
    fixture.detectChanges();
    expect(picker.disabled).toBeFalse();
    fixture.nativeElement.querySelector('[aria-label="Remove Missing layer: Missing"]').click();
    expect(c.entity.requiredSlots).toEqual([c.story.slots[0]]);
    picker.valueChange.emit([c.story.slots[0], c.story.slots[1]]);
    expect(c.entity.requiredSlots).toEqual(c.story.slots.slice(0, 2));
    expect(parent.requiredSlots).toEqual([c.story.slots[0], 'Missing']);
    c.setSlotsOverride(false);
    expect(c.resolved.requiredSlots).toEqual(parent.requiredSlots);
  });
  it('creates and configures a granted variable from Equipment when no character variables exist', async () => {
    const fixture = TestBed.createComponent(EquipmentEditorComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    c.story.flags = [];
    c.entity = c.story.entities.find((e) => e.id === 'dagger');
    c.entity.flagGrants = [];
    const changed = spyOn(c.changed, 'emit');
    dialogs.createInput.and.resolveTo(undefined);
    await c.createGrantVariable();
    expect(c.story.flags).toEqual([]);
    expect(changed).not.toHaveBeenCalled();
    dialogs.createInput.and.resolveTo(' Protected from curses ');
    c.section = 'Effects';
    fixture.detectChanges();
    const create = Array.from(fixture.nativeElement.querySelectorAll('button') as NodeListOf<HTMLButtonElement>).find((b) => b.textContent.trim() === 'Create effect');
    expect(create).toBeDefined();
    create.click();
    await fixture.whenStable();
    fixture.detectChanges();
    const variable = c.story.flags[0];
    expect(variable).toEqual(jasmine.objectContaining({ name: 'Protected from curses', scope: 'character', type: 'boolean', initial: false }));
    expect(c.entity.flagGrants).toEqual([{ flag: variable.id, when: 'equipped', suppressed: false }]);
    expect(c.selectedEffects).toEqual([variable.id]);
    expect(fixture.nativeElement.textContent).not.toContain('While owned');
    expect(fixture.nativeElement.textContent).not.toContain('While equipped');
    c.setGrant(variable.id, 'equipped');
    expect(c.resolved.flagGrants[0].when).toBe('equipped');
    c.removeInvalidGrant(variable.id);
    expect(c.story.flags).toEqual([variable]);
    expect(c.effectOptions.map((option) => option.value)).toEqual([variable.id]);
  });
  it('settles when opening equipment Effects with automatic rendering and still edits inherited effects', async () => {
    const fixture = TestBed.createComponent(EquipmentEditorComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    upgradeEquipmentTypes(c.story);
    c.entity = c.story.entities.find((e) => e.id === 'dagger');
    c.section = 'Effects';
    const selected = Object.getOwnPropertyDescriptor(EquipmentEditorComponent.prototype, 'selectedEffects').get;
    const options = Object.getOwnPropertyDescriptor(EquipmentEditorComponent.prototype, 'effectOptions').get;
    const fallbackValue = selected.call(c),
      fallbackOptions = options.call(c);
    let reads = 0;
    // Bound the regression so a broken control fails instead of freezing Chrome.
    spyOnProperty(c, 'selectedEffects', 'get').and.callFake(() => (++reads < 100 ? selected.call(c) : fallbackValue));
    spyOnProperty(c, 'effectOptions', 'get').and.callFake(() => (reads < 100 ? options.call(c) : fallbackOptions));
    const changed = spyOn(c.changed, 'emit');
    const before = copy(c.story);
    fixture.autoDetectChanges();
    await fixture.whenStable();
    expect(reads).toBeLessThan(50);
    expect(c.story).toEqual(before);
    expect(changed).not.toHaveBeenCalled();
    fixture.nativeElement.querySelector('[aria-label="Remove Armed"]').click();
    await fixture.whenStable();
    expect(c.selectedEffects).toEqual(['ready']);
    expect(c.entity.flagGrants).toContain(jasmine.objectContaining({ flag: 'armed', suppressed: true }));
    expect(changed).toHaveBeenCalledTimes(1);
    expect(reads).toBeLessThan(100);
  });
  it('selects type effects in one control and suppresses or restores inherited effects without editing the type', async () => {
    const fixture = TestBed.createComponent(EquipmentEditorComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    upgradeEquipmentTypes(c.story);
    const equipment = c.story.entities.find((e) => e.id === 'dagger');
    const type = c.story.entities.find((e) => e.id === equipment.parentId);
    c.entity = type;
    c.section = 'Effects';
    const changed = spyOn(c.changed, 'emit');
    fixture.detectChanges();
    await fixture.whenStable();
    let picker = fixture.debugElement.query(By.directive(MultiselectComponent)).componentInstance as MultiselectComponent;
    expect(picker.value).toEqual(['armed', 'ready']);
    expect(changed).not.toHaveBeenCalled();
    picker.valueChange.emit(['armed']);
    expect(type.flagGrants).toEqual([{ flag: 'armed', when: 'equipped' }]);
    expect(changed).toHaveBeenCalledTimes(1);
    const originalType = copy(type);
    c.entity = equipment;
    fixture.detectChanges();
    await fixture.whenStable();
    picker = fixture.debugElement.query(By.directive(MultiselectComponent)).componentInstance as MultiselectComponent;
    expect(picker.value).toEqual(['armed']);
    picker.valueChange.emit(['ready', 'ready', 'missing']);
    expect(c.selectedEffects).toEqual(['ready']);
    expect(equipment.flagGrants).toContain(jasmine.objectContaining({ flag: 'armed', suppressed: true }));
    picker.valueChange.emit(['armed']);
    expect(equipment.flagGrants).toEqual([]);
    expect(c.selectedEffects).toEqual(['armed']);
    expect(type).toEqual(originalType);
    c.section = 'General';
    c.entity = type;
    fixture.detectChanges();
    expect(fixture.nativeElement.textContent).not.toContain('Shared defaults for equipment');
  });
  it('keeps missing item effects visible and removable while selecting multiple valid owned effects', async () => {
    const fixture = TestBed.createComponent(EntityFlagsComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities.find((e) => e.id === 'apple');
    c.entity.flagGrants = [{ flag: 'missing', when: 'owned' }];
    fixture.detectChanges();
    await fixture.whenStable();
    fixture.detectChanges();
    expect(fixture.nativeElement.textContent).toContain('Missing or incompatible effect: missing');
    const picker = fixture.debugElement.query(By.directive(MultiselectComponent)).componentInstance as MultiselectComponent;
    picker.valueChange.emit(['missing', 'armed', 'ready', 'ready']);
    expect(c.selectedEffects).toEqual(['missing', 'armed', 'ready']);
    expect(c.entity.flagGrants.every((g) => g.when === 'owned')).toBeTrue();
    fixture.detectChanges();
    await fixture.whenStable();
    fixture.nativeElement.querySelector('[aria-label="Remove Missing or incompatible effect: missing"]').click();
    expect(c.selectedEffects).toEqual(['armed', 'ready']);
  });
  it('uses multiselects for scene-test choices and knowledge without changing the story or saved game', async () => {
    const fixture = TestBed.createComponent(PlayerComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    c.testScene = c.story.start;
    c.ngOnChanges();
    const storyBefore = copy(c.story);
    fixture.detectChanges();
    await fixture.whenStable();
    const pickers = fixture.debugElement.queryAll(By.directive(MultiselectComponent)).map((d) => d.componentInstance as MultiselectComponent);
    const choices = pickers.find((p) => p.label === 'Previous choices');
    const known = pickers.find((p) => p.label === 'Known information');
    const choice = c.authoredChoices[0].id;
    choices.valueChange.emit([choice, choice]);
    known.valueChange.emit(['player', 'apple']);
    expect(c.setup.chosen).toEqual([choice]);
    expect(c.setup.known).toEqual(['player', 'apple']);
    await c.start();
    expect(c.game.state.chosen).toEqual([choice]);
    expect(c.choices).toEqual([]);
    const gameBefore = copy(c.game);
    choices.valueChange.emit([]);
    known.valueChange.emit([]);
    expect(c.setup.chosen).toEqual([]);
    expect(c.setup.known).toEqual([]);
    expect(c.game).toEqual(gameBefore);
    expect(c.story).toEqual(storyBefore);
    expect(persistence.commit).not.toHaveBeenCalled();
  });
  it('adds eligible existing grants once and keeps inherited grant controls available', () => {
    const c = TestBed.createComponent(EquipmentEditorComponent).componentInstance;
    c.story = inventoryFixture();
    const variable = { ...newFlag(), scope: 'character' as const };
    c.story.flags = [variable, newFlag(), { ...newFlag(), scope: 'character', type: 'number' }, { ...newFlag(), scope: 'character', type: 'text' }];
    c.entity = c.story.entities.find((e) => e.id === 'dagger');
    c.entity.flagGrants = [];
    expect(c.effectOptions.map((option) => option.value)).toEqual([variable.id]);
    c.setEffects([variable.id]);
    c.setEffects([variable.id]);
    expect(c.entity.flagGrants.length).toBe(1);
    const parent = c.entity;
    c.entity = { ...copy(parent), id: 'variant', parentId: parent.id, properties: [], flagGrants: [] };
    c.story.entities.push(c.entity);
    expect(c.selectedEffects).toEqual([variable.id]);
    expect(c.ownGrant(variable.id)).toBeUndefined();
    c.setEffects([]);
    expect(c.resolved.flagGrants).toEqual([]);
    c.setEffects([variable.id]);
    expect(c.resolved.flagGrants).toEqual(parent.flagGrants);
  });
  it('adds separate copies to the selected character without changing templates or other inventories', () => {
    const c = TestBed.createComponent(CharacterEquipmentComponent).componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities.find((e) => e.id === 'player');
    const templates = copy(c.templates),
      existing = copy(c.story.copies);
    c.selected = 'dagger';
    c.addCopy();
    c.addCopy();
    c.addCopy();
    const added = c.story.copies.slice(existing.length);
    expect(new Set(added.map((item) => item.id)).size).toBe(3);
    expect(new Set(added.map((item) => item.name)).size).toBe(3);
    expect(added.every((item) => item.owner === 'player' && !item.equipped)).toBeTrue();
    c.setCopyValue(added[0], 'durability', 20);
    c.setCopyValue(added[1], 'durability', 60);
    const game = startGame(c.story, 'Starting swords');
    expect(added.map((item) => game.state.copyStates[item.id].values['durability'])).toEqual([20, 60, 100]);
    expect(c.templates).toEqual(templates);
    expect(c.story.copies.slice(0, existing.length)).toEqual(existing);
    c.selected = 'missing';
    c.addCopy();
    expect(c.story.copies.length).toBe(existing.length + 3);
  });
  it('reassigns existing equipment with stable identity and independent duplicate overrides', async () => {
    const fixture = TestBed.createComponent(CharacterEquipmentComponent),
      c = fixture.componentInstance;
    c.story = inventoryFixture();
    c.entity = c.story.entities.find((e) => e.id === 'player');
    const item = c.copies[0];
    item.values = { durability: 42 };
    item.keyItems = ['apple'];
    const original = copy(c.story),
      changed = spyOn(c.changed, 'emit');
    fixture.detectChanges();
    await fixture.whenStable();
    expect(c.story).toEqual(original);
    expect(changed).not.toHaveBeenCalled();
    c.removeFromInventory(item);
    expect(c.unassigned).toContain(item);
    expect(item.equipped).toBeFalse();
    c.entity = c.story.entities.find((e) => e.id === 'npc');
    c.existingId = item.id;
    c.addExisting();
    expect(c.copies).toContain(item);
    expect(item.values).toEqual({ durability: 42 });
    expect(item.keyItems).toEqual(['apple']);
    expect(c.story.scenes).toEqual(original.scenes);
    expect(c.story.copies.length).toBe(original.copies.length);
    c.duplicateCopy(item);
    const duplicate = c.story.copies.at(-1);
    duplicate.values['durability'] = 17;
    duplicate.keyItems.push('another-key');
    expect(item.values['durability']).toBe(42);
    expect(item.keyItems).toEqual(['apple']);
    expect(duplicate.owner).toBe('npc');
    dialogs.createConfirmation.and.resolveTo(false);
    await c.deleteCopy(item);
    expect(c.story.copies).toContain(item);
    dialogs.createConfirmation.and.resolveTo(true);
    await c.deleteCopy(item);
    expect(c.story.copies).not.toContain(item);
  });
  it('shows equipped definitions once and keeps shared properties readable', async () => {
    const f = TestBed.createComponent(PlayerComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    const game = startGame(c.story, 'Reader');
    applyEffect(c.story, game.state, { kind: 'equip', target: 'dagger-1', actor: 'player', value: '' });
    persistence.data.playthroughs = [game];
    f.detectChanges();
    await f.whenStable();
    expect(c.inventory.filter((e) => e.kind === 'equipment').length).toBe(2);
    expect(c.equipment.map((e) => e.id)).toEqual(['dagger-1']);
    expect(f.nativeElement.textContent).toContain('Equipment');
    c.inspected = 'dagger-1';
    f.detectChanges();
    await f.whenStable();
    const inspector = f.nativeElement.querySelector('aside');
    expect(inspector.textContent).toContain('Durability');
    expect(inspector.textContent).toContain('100');
    expect(f.nativeElement.textContent).not.toContain('Private');
  });
  it('keeps inventory scene tests and undo isolated from saves and definitions', async () => {
    const f = TestBed.createComponent(PlayerComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    c.testScene = c.story.start;
    c.ngOnChanges();
    const before = copy(c.story);
    c.setAmount('player', 'apple', 8);
    c.setVariable(variableKey('copy', 'dagger-1', 'durability'), 25);
    c.equipItem('player', 'dagger-1', true);
    await c.start();
    expect(c.game.state.copyStates['dagger-1'].values['durability']).toBe(25);
    await c.select(c.passage.choices[0].id);
    c.undo();
    expect(c.game.state.copyStates['dagger-1'].values['durability']).toBe(25);
    expect(c.game.status).toBe('active');
    expect(c.story).toEqual(before);
    expect(persistence.commit).not.toHaveBeenCalled();
  });
  it('offers quantity actions for both item categories without unique transfers', async () => {
    const f = TestBed.createComponent(OutcomeEditorComponent),
      c = f.componentInstance;
    c.story = inventoryFixture();
    c.steps = [{ id: 'step', kind: 'effect', effect: { kind: 'giveQuantity', target: 'dagger', actor: 'player', value: 1 } }];
    f.detectChanges();
    await f.whenStable();
    const step = c.steps[0];
    if (step.kind !== 'effect') throw new Error('fixture');
    expect(c.effectObjects(step.effect).map((e) => e.id)).toEqual(['apple']);
    step.effect.kind = 'removeQuantity';
    step.effect.target = 'dagger';
    c.targetChanged(step.effect);
    f.detectChanges();
    await f.whenStable();
    expect(c.effectObjects(step.effect).map((e) => e.id)).toEqual(['apple']);
    expect(step.effect.value).toBe(1);
    expect(f.nativeElement.querySelector('option[value=transfer]')).toBeNull();
    expect(f.nativeElement.textContent).toContain('Equipped items are excluded');
  });
  it('disables filtered/boundary moves and emits a single persisted move', () => {
    const f = TestBed.createComponent(ReorderComponent),
      c = f.componentInstance;
    const first = { id: 'first' },
      second = { id: 'second' };
    c.items = [first, second];
    c.label = 'item';
    const change = jasmine.createSpy();
    c.changed.subscribe(change);
    f.detectChanges();
    const buttons = f.nativeElement.querySelectorAll('button');
    expect(buttons[0].disabled).toBeTrue();
    c.disabled = true;
    f.detectChanges();
    buttons[1].click();
    expect(c.items[0]).toBe(first);
    expect(change).not.toHaveBeenCalled();
    c.disabled = false;
    f.detectChanges();
    buttons[1].click();
    expect(c.items[1]).toBe(first);
    expect(change).toHaveBeenCalledTimes(1);
  });
  it('reserves no room for reordering a single entry and restores controls as the list grows', () => {
    const fixture = TestBed.createComponent(ReorderComponent),
      c = fixture.componentInstance;
    c.items = ['first'];
    const changed = jasmine.createSpy();
    c.changed.subscribe(changed);
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('button')).toBeNull();
    expect(fixture.nativeElement.getBoundingClientRect().width).toBe(0);
    c.items.push('second');
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelectorAll('button').length).toBe(2);
    expect(fixture.nativeElement.getBoundingClientRect().width).toBeGreaterThan(0);
    expect(changed).not.toHaveBeenCalled();
  });
});
