export const questionsGeneric = [
  'nikdy som si neochutnal šušeň',
  'nikdy som neukradol niečo nad 10 eur',
  'nikdy som nepodaroval darček ďalej',
  'nikdy som neupchal toaletu na návšteve',
  'nikdy som neprezradil niekoho tajomstvo',
  'nikdy som si nevytvoril falošný profil na sociálnej sieti',
  'nikdy som sa ako dospelý tak nesmial, že som sa pocikal',
  'nikdy som sa ako dospelý neposral',
  'nikdy som sa netváril, že som si zabudol peňaženku, lebo som nechcel platiť',
  'nikdy som nepochyboval o svojej sexuálnej orientácii',
  'nikdy som nesledoval susedov ďalekohladom',
  'nikdy som si neprdol v uzavretom priestore a tváril sa, akoby sa nič nestalo',
  'nikdy som nemusel utekať o život',
  'nikdy som sa nemusel v nebezpečnej situácii schovávať',
  'nikdy som nepokreslil spiaceho kamaráta',
  'nikdy som nezaspal opitý na verejnosti',
  'nikdy som sa nevkradol na cudziu párty, kde som nikoho nepoznal',
  'nikdy som sa neodmietol ísť na kúpalisko preto, že som sa hanbil za svoju postavu',
  'nikdy som sa z hlboka nenadýchol svojho prdu',
  'nikdy som nebol vyhodený z podniku',
  'nikdy som neochutnal žrádlo pre zvieratá',
  'nikdy som počas tejto hry neklamal',
  'nikdy som sa aspoň 3 dni neosprchoval',
  'nikdy som si aspoň 3 dni neumyl zuby',
  'nikdy som nikoho nepodplatil',
  'nikdy som nebol na verejnosti úplne nahý',
  'nikdy som nenastúpil do nesprávneho autobusu',
  'nikdy som sa nepozeral na svoju riť v zrkadle',
];

export const questionsNsfw = [
  'nikdy som si nezaplatil za porno',
  'nikdy som nikoho nepodviedol',
  'nikdy som sa nevykašlal na rande bez oznámenia',
  'nikdy som nikomu omylom neposlal nahú fotku',
  'nikdy som nekúpil drink niekomu, koho som nepoznal',
  'nikdy som nebol na rande s viacero osobami za jeden deň',
  'nikdy som nehladal vzťah na zoznamke',
  'nikdy som nehladal sex na zoznamke',
  'nikdy som nehľadal návod, ako niekoho zbaliť',
  'nikdy som nehľadal návod, ako sa bozkávať',
  'nikdy som nehľadal návod, ako mať sex',
  'nikdy som nepočul susedov alebo spolubývajúcich mať sex',
  'nikdy som si nemusel zakrývať cucflek',
  'nikdy som s niekým neflirtoval len preto, aby niekto iný žiarlil',
  'nikdy som nebol v gay bare',
  'nikdy som opitý nepísal ex, že mi chýba',
  'nikdy som netúžil po partnerke svojho kamaráta',
  'nikdy som si s nikým neporovnával svoju pýchu alebo prsia',
];

export const questionsSpicy = [
  'nikdy som si pri sexe nepredstavoval, že som s niekym iným',
  'nikdy som nemal sex s niekým, kde vekový rozdiel bol aspoň 5 rokov',
  'nikdy som s nikým nestrávil celý deň v posteli',
  'nikdy som nemal sex, keď sa na nás pozeralo domáce zvieratko',
  'nikdy som nemal sex s osobou rovnakého pohlavia',
  'nikdy som nikomu neplatil za sex',
  'nikdy som nemal erotické predstavy o niekom z tejto miestnosti',
  'nikdy som nemal sex vo výťahu',
  'nikdy som nemal sex v skúšobnej kabínke',
  'nikdy som nemal sex v aute',
  'nikdy som nemal sex v prírode',
  'nikdy som nemal sex na pláži',
  'nikdy som nemal sex na záchodoch',
  'nikdy som nikomu nerobil striptíz',
  'nikdy som nepoužil erotickú hračku alebo pomôcku',
  'nikdy som nenosil spodné prádlo opačného pohlavia',
  'nikdy som sa nepokúšal niečo si vopchať do zadku',
  'nikdy som neskúsil niečo z BDSM',
  'nikdy som neskúsil roleplay',
  'nikdy som sa nezobudil na orálny sex',
  'nikdy som nerealizoval svoje sexuálne fantázie',
  'nikdy som nemal sex bez ochrany',
  'nikdy sme si s iným párom nevymenili partnerky',
  'nikdy som nedával partnerke masáž celého tela',
  'nikdy som nebol na masáži celého tela'
];